/* tslint:disable */
/* eslint-disable */
/**
 * Live Leaderboards
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface Course
 */
export interface Course {
  /**
   *
   * @type {any}
   * @memberof Course
   */
  name: any | null;
  /**
   *
   * @type {any}
   * @memberof Course
   */
  tees?: any | null;
  /**
   *
   * @type {any}
   * @memberof Course
   */
  holes: any | null;
}

/**
 * Check if a given object implements the Course interface.
 */
export function instanceOfCourse(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "name" in value;
  isInstance = isInstance && "holes" in value;

  return isInstance;
}

export function CourseFromJSON(json: any): Course {
  return CourseFromJSONTyped(json, false);
}

export function CourseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Course {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: json["name"],
    tees: !exists(json, "tees") ? undefined : json["tees"],
    holes: json["holes"],
  };
}

export function CourseToJSON(value?: Course | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    tees: value.tees,
    holes: value.holes,
  };
}
