/* tslint:disable */
/* eslint-disable */
/**
 * Live Leaderboards
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface HoleScore
 */
export interface HoleScore {
  /**
   *
   * @type {any}
   * @memberof HoleScore
   */
  hole: any | null;
  /**
   *
   * @type {any}
   * @memberof HoleScore
   */
  score: any | null;
}

/**
 * Check if a given object implements the HoleScore interface.
 */
export function instanceOfHoleScore(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "hole" in value;
  isInstance = isInstance && "score" in value;

  return isInstance;
}

export function HoleScoreFromJSON(json: any): HoleScore {
  return HoleScoreFromJSONTyped(json, false);
}

export function HoleScoreFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): HoleScore {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    hole: json["hole"],
    score: json["score"],
  };
}

export function HoleScoreToJSON(value?: HoleScore | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    hole: value.hole,
    score: value.score,
  };
}
