/* tslint:disable */
/* eslint-disable */
/**
 * Live Leaderboards
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface Hole
 */
export interface Hole {
  /**
   *
   * @type {any}
   * @memberof Hole
   */
  hole: any | null;
  /**
   *
   * @type {any}
   * @memberof Hole
   */
  par: any | null;
  /**
   *
   * @type {any}
   * @memberof Hole
   */
  distanceYards?: any | null;
  /**
   *
   * @type {any}
   * @memberof Hole
   */
  strokeIndex?: any | null;
}

/**
 * Check if a given object implements the Hole interface.
 */
export function instanceOfHole(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "hole" in value;
  isInstance = isInstance && "par" in value;

  return isInstance;
}

export function HoleFromJSON(json: any): Hole {
  return HoleFromJSONTyped(json, false);
}

export function HoleFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Hole {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    hole: json["hole"],
    par: json["par"],
    distanceYards: !exists(json, "distanceYards")
      ? undefined
      : json["distanceYards"],
    strokeIndex: !exists(json, "strokeIndex") ? undefined : json["strokeIndex"],
  };
}

export function HoleToJSON(value?: Hole | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    hole: value.hole,
    par: value.par,
    distanceYards: value.distanceYards,
    strokeIndex: value.strokeIndex,
  };
}
