/* tslint:disable */
/* eslint-disable */
/**
 * Live Leaderboards
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { Course } from "./Course";
import { CourseFromJSON, CourseFromJSONTyped, CourseToJSON } from "./Course";

/**
 *
 * @export
 * @interface RoundRequest
 */
export interface RoundRequest {
  /**
   *
   * @type {any}
   * @memberof RoundRequest
   */
  title?: any | null;
  /**
   *
   * @type {Course}
   * @memberof RoundRequest
   */
  course: Course;
  /**
   *
   * @type {any}
   * @memberof RoundRequest
   */
  players: any | null;
}

/**
 * Check if a given object implements the RoundRequest interface.
 */
export function instanceOfRoundRequest(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "course" in value;
  isInstance = isInstance && "players" in value;

  return isInstance;
}

export function RoundRequestFromJSON(json: any): RoundRequest {
  return RoundRequestFromJSONTyped(json, false);
}

export function RoundRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RoundRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    title: !exists(json, "title") ? undefined : json["title"],
    course: CourseFromJSON(json["course"]),
    players: json["players"],
  };
}

export function RoundRequestToJSON(value?: RoundRequest | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    title: value.title,
    course: CourseToJSON(value.course),
    players: value.players,
  };
}
