openapi: 3.1.0
info:
  title: Live Leaderboards
  summary: Send scores and see live updates of your friends playing golf.
  version: 0.1.0
  contact:
    name: Evertras
    url: https://github.com/Evertras/live-leaderboards

servers:
  - url: http://localhost:8417
    description: Local server

paths:
  /round:
    post:
      tags:
        - round
      description: Creates a new round
      requestBody:
        description: Round information
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/RoundRequest"
            examples:
              simple:
                $ref: "#/components/examples/RoundPebble"
      responses:
        "201":
          description: Round created successfully
          content:
            application/json:
              examples:
                success:
                  summary: "Success"
                  value:
                    id: 43187519-9C19-49CB-91BE-C4231178CEB9
              schema:
                $ref: "#/components/schemas/CreatedRound"
  /round/{roundID}:
    get:
      tags:
        - round
      description: Gets current round information
      responses:
        "200":
          description: Round retrieved successfully
          content:
            application/json:
              examples:
                success:
                  summary: "Success"
              schema:
                $ref: "#/components/schemas/Round"

components:
  examples:
    RoundPebble:
      summary: Pebble Beach
      value:
        title: Super Pebble Showdown
        course:
          name: Pebble Beach
          tees: White
          holes:
            - hole: 1
              par: 4
              distance: 337
              strokeIndex: 6
            - hole: 2
              par: 5
              distance: 458
              strokeIndex: 10
            - hole: 3
              par: 4
              distance: 340
              strokeIndex: 12
            - hole: 4
              par: 4
              distance: 290
              strokeIndex: 16
            - hole: 5
              par: 3
              distance: 134
              strokeIndex: 14
            - hole: 6
              par: 5
              distance: 465
              strokeIndex: 2
            - hole: 7
              par: 3
              distance: 94
              strokeIndex: 18
            - hole: 8
              par: 4
              distance: 364
              strokeIndex: 4
            - hole: 9
              par: 4
              distance: 436
              strokeIndex: 8
            - hole: 10
              par: 4
              distance: 408
              strokeIndex: 3
            - hole: 11
              par: 4
              distance: 338
              strokeIndex: 9
            - hole: 12
              par: 3
              distance: 176
              strokeIndex: 17
            - hole: 13
              par: 4
              distance: 370
              strokeIndex: 7
            - hole: 14
              par: 5
              distance: 490
              strokeIndex: 1
            - hole: 15
              par: 4
              distance: 338
              strokeIndex: 13
            - hole: 16
              par: 4
              distance: 368
              strokeIndex: 11
            - hole: 17
              par: 4
              distance: 166
              strokeIndex: 15
            - hole: 18
              par: 5
              distance: 506
              strokeIndex: 5
        players:
          - name: Evertras
          - name: John Rahm
          - name: 松山英樹
          - name: John Daly
  schemas:
    HoleNumber:
      type: integer
      minimum: 1
      maximum: 36
      examples:
        - 1
        - 2
        - 3
    Hole:
      type: object
      required:
        - hole
        - par
      properties:
        hole:
          $ref: "#/components/schemas/HoleNumber"
        par:
          type: integer
          minimum: 3
          maximum: 5
          examples:
            - 3
            - 4
            - 5
        distance:
          type: integer
          minimum: 1
          maximum: 1000
          examples:
            - 124
            - 380
            - 602
        strokeIndex:
          type: integer
          minimum: 1
          maximum: 18
          examples:
            - 14
            - 8
            - 11
    Course:
      type: object
      required:
        - name
        - holes
      properties:
        name:
          maxLength: 50
          type: string
          examples:
            - Pebble Beach
        tees:
          maxLength: 20
          type: string
          examples:
            - White
        holes:
          type: array
          minItems: 1
          maxItems: 36
          items:
            $ref: "#/components/schemas/Hole"
    PlayerData:
      type: object
      required:
        - name
      properties:
        name:
          examples:
            - John Rahm
            - 松山英樹
          type: string
          minLength: 1
          maxLength: 50
    PlayerGroup:
      type: array
      minItems: 1
      maxItems: 12
      uniqueItems: true
      items:
        $ref: "#/components/schemas/PlayerData"
    RoundID:
      type: string
      examples:
        - "7F4EF598-1F47-4E01-8408-EDDC71FE53E9"
    RoundTitle:
      maxLength: 50
      type: string
      examples:
        - Super Showdown
    RoundRequest:
      type: object
      required:
        - course
        - players
      properties:
        title:
          $ref: "#/components/schemas/RoundTitle"
        course:
          $ref: "#/components/schemas/Course"
        players:
          $ref: "#/components/schemas/PlayerGroup"
    CreatedRound:
      type: object
      required:
        - id
      properties:
        id:
          $ref: "#/components/schemas/RoundID"
    Round:
      type: object
      required:
        - id
        - title
        - course
        - players
      properties:
        id:
          $ref: "#/components/schemas/RoundID"
        title:
          $ref: "#/components/schemas/RoundTitle"
        course:
          $ref: "#/components/schemas/Course"
        players:
          type: array
          items:
            allOf:
              - $ref: "#/components/schemas/PlayerData"
              - type: object
                properties:
                  scores:
                    $ref: "#/components/schemas/PlayerScore"
    HoleScore:
      type: object
      required:
        - hole
        - score
      properties:
        hole:
          $ref: "#/components/schemas/HoleNumber"
        score:
          type: integer
          minimum: 1
          maximum: 30
          examples:
            - 4
    PlayerScore:
      type: array
      minItems: 1
      maxItems: 36
      items:
        $ref: "#/components/schemas/HoleScore"

tags:
  - name: round
    description: Round operations
